### ISSUE TITLE
US1 - List of goals

### ISSUE THREAD

**Issue by CorneliusMoe** [CorneliusMoe/Capstone-Cornelius#1]
## Value proposition

As a User 
I want to see a list of my goals
So that I can remember and track them

## Description

![Image](https://user-images.githubusercontent.com/132472335/250935192-ab51754e-5d18-4c59-becf-cdcb71ba7663.png)

## Acceptance criteria

- [ ] The page has a heading called "my Goals"
- [ ] The goals each have their own card
- [ ] The list should be vertically sorted
- [ ] Every card contains the title of the goal

## Tasks

- [ ] Create a component that returns a heading
- [ ] Create a card component that returns the name of the goal
