### ISSUE TITLE
US2 - Goal in Detail

### ISSUE THREAD

**Issue by CorneliusMoe** [CorneliusMoe/Capstone-Cornelius#2]
## Value proposition

As a User 
I want to be able to view the details of a specific goal when I click on it in the list of goals
So that I can see the detailed objectives of that goal

## Description

![Image](https://user-images.githubusercontent.com/132472335/251230762-4e530496-4a26-4956-815d-14b494819c4e.png)

## Acceptance criteria

- [ ] Clicking a goal should lead to the details of that goal
- [ ] The details page should show a list of the details
- [ ] It should contain a header and the associated text
- [ ] The details should be vertically sorted
- [ ] At the bottom of the details page there should be a button that leads back to the list of goals

## Tasks

- [ ] Create a `feature` branch
- [ ] Create a new page `GoalDetails`
- [ ] Make the goals clickable with a link to the `GoalDetails` page
- [ ] Create a card component that returns the details of a specific goal
- [ ] Render the card component in the `GoalDetails` page
- [ ] The details must contain 5 Headings and 5 details
- [ ] Align the goals vertically
- [ ] Create a Button that leads back to the list of goals

**Comment by AliaksandraNovikava** [comment]
Your idea for this user story looks nice.
One task is missing:
`The details page should show a list of the details`: here you suggest a different page (`details page`), but don't have it in your tasks list. Where should the card component that returns the details of a specific goal be rendered?
You probable want first to create a new page that renders your details component?

**Comment by CorneliusMoe** [comment]
Hi Alex, thank you for the input. This is really helpful as I was struggling with writing the tasks. I changed them according to your recommendations. 👍

**Comment by josch87** [comment]
Looks very good.

As a developer I just wouldn't get the AC `The details should be vertically sorted`. By which criteria should the details be sorted? Alphabetically by their label? Or do you mean they need to be vertical list items?

**Comment by CorneliusMoe** [comment]
Aljoscha, 

thank you for the positive feedback. I changed my US accordingly.

**Comment by ThysBat** [comment]
LGTM 🚀
