### ISSUE TITLE
US3 - Delete a Goal

### ISSUE THREAD

**Issue by CorneliusMoe** [CorneliusMoe/Capstone-Cornelius#3]
## Value proposition

As a User 
I want to be able to delete a goal
So that I can remove it from my list of goals after i have completed it

## Description

![Image](https://user-images.githubusercontent.com/132472335/251472649-2d2d7496-f0fd-478a-9c76-fdb7d063e8b3.png)

## Acceptance criteria

- [ ] A `button` exists that is called "Delete"
- [ ] On clicking the delete button a confirmation dialogue should appear
- [ ] On cancel, the confirmation dialogue should close and the process should be cancelled
- [ ] On confirm the Goal should be deleted
- [ ] In the List of goals the deleted goal should be gone

## Tasks

- [ ] Create a feature branch
- [ ] Create a `ConfirmationDialog` component
- [ ] Integrate the `ConfirmationDialog` component in the GoalDetail page
- [ ] Set up state using React's `useState` to manage the visibility of the confirmation dialog.
- [ ] Implement the event handler for the "Delete" button that opens the confirmation dialog.
- [ ] Implement a `handleConfirmDelete` function to perform the deletion action.
- [ ] Implement a `handleCancelDelete` function to close the confirmation dialog.

**Comment by ArnelaKapllani** [comment]
Looks very goog :)
just a small detail: does the "back to my projects" button have any function here? If not maybe you have to remove it from the wireframe :)

**Comment by CorneliusMoe** [comment]
Thanks :) the back to my projects button is included in US2. I should have included that information in this US.

**Comment by SelcoD** [comment]
LGTM !
